DAY_IN_SECONDS: int = 24 * 60 * 60

ORDERS = [
    "power",
    "anger",
    "brilliance",
    "detection",
    "enlightenment",
    "fox",
    "fury",
    "giants",
    "perfection",
    "reflection",
    "skill",
    "titans",
    "twins",
    "vitriol",
    "rage",
    "protection",
]


Resources = {
    1: "wood",
    2: "stone",
    3: "coal",
    4: "copper",
    5: "obsidian",
    6: "silver",
    7: "ironwood",
    8: "cold iron",
    9: "gold",
    10: "hartwood",
    11: "diamonds",
    12: "sapphire",
    13: "ruby",
    14: "deep crystal",
    15: "ignium",
    16: "ethereal silica",
    17: "true ice",
    18: "twilight quartz",
    19: "alchemical silver",
    20: "adamantine",
    21: "mithral",
    22: "dragonhide",
    253: "Lords",
    254: "wheat",
    255: "fish",
}
