# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0btypes.proto\x12\x05types\x1a\x0cschema.proto"\x9d\x01\n\rWorldMetadata\x12\x15\n\rworld_address\x18\x01'
    b" \x01(\t\x12\x18\n\x10world_class_hash\x18\x02 \x01(\t\x12\x18\n\x10\x65xecutor_address\x18\x03"
    b" \x01(\t\x12\x1b\n\x13\x65xecutor_class_hash\x18\x04 \x01(\t\x12$\n\x06models\x18\x05"
    b' \x03(\x0b\x32\x14.types.ModelMetadata"}\n\rModelMetadata\x12\x0c\n\x04name\x18\x01'
    b" \x01(\t\x12\x13\n\x0bpacked_size\x18\x02 \x01(\r\x12\x15\n\runpacked_size\x18\x03"
    b" \x01(\r\x12\x12\n\nclass_hash\x18\x04 \x01(\t\x12\x0e\n\x06layout\x18\x05 \x01(\x0c\x12\x0e\n\x06schema\x18\x06"
    b' \x01(\x0c"5\n\x05Model\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x07members\x18\x02'
    b' \x03(\x0b\x32\r.types.Member"3\n\x06\x45ntity\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x1c\n\x06models\x18\x02'
    b' \x03(\x0b\x32\x0c.types.Model"*\n\x0cStorageEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t"L\n\x0bStorageDiff\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12,\n\x0fstorage_entries\x18\x02'
    b' \x03(\x0b\x32\x13.types.StorageEntry"7\n\nEntityDiff\x12)\n\rstorage_diffs\x18\x01'
    b' \x03(\x0b\x32\x12.types.StorageDiff"J\n\x0c\x45ntityUpdate\x12\x12\n\nblock_hash\x18\x01'
    b" \x01(\t\x12&\n\x0b\x65ntity_diff\x18\x02"
    b' \x01(\x0b\x32\x11.types.EntityDiff"E\n\x05Query\x12\x1d\n\x06\x63lause\x18\x01'
    b" \x01(\x0b\x32\r.types.Clause\x12\r\n\x05limit\x18\x02 \x01(\r\x12\x0e\n\x06offset\x18\x03"
    b' \x01(\r"\x8e\x01\n\x06\x43lause\x12!\n\x04keys\x18\x01'
    b" \x01(\x0b\x32\x11.types.KeysClauseH\x00\x12%\n\x06member\x18\x02"
    b" \x01(\x0b\x32\x13.types.MemberClauseH\x00\x12+\n\tcomposite\x18\x03"
    b' \x01(\x0b\x32\x16.types.CompositeClauseH\x00\x42\r\n\x0b\x63lause_type")\n\nKeysClause\x12\r\n\x05model\x18\x01'
    b' \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\x0c"w\n\x0cMemberClause\x12\r\n\x05model\x18\x01'
    b" \x01(\t\x12\x0e\n\x06member\x18\x02 \x01(\t\x12+\n\x08operator\x18\x03"
    b" \x01(\x0e\x32\x19.types.ComparisonOperator\x12\x1b\n\x05value\x18\x04"
    b' \x01(\x0b\x32\x0c.types.Value"j\n\x0f\x43ompositeClause\x12\r\n\x05model\x18\x01'
    b" \x01(\t\x12(\n\x08operator\x18\x02 \x01(\x0e\x32\x16.types.LogicalOperator\x12\x1e\n\x07\x63lauses\x18\x03"
    b' \x03(\x0b\x32\r.types.Clause*"\n\x0fLogicalOperator\x12\x07\n\x03\x41ND\x10\x00\x12\x06\n\x02OR\x10\x01*G\n\x12\x43omparisonOperator\x12\x06\n\x02\x45Q\x10\x00\x12\x07\n\x03NEQ\x10\x01\x12\x06\n\x02GT\x10\x02\x12\x07\n\x03GTE\x10\x03\x12\x06\n\x02LT\x10\x04\x12\x07\n\x03LTE\x10\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "types_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_LOGICALOPERATOR"]._serialized_start = 1174
    _globals["_LOGICALOPERATOR"]._serialized_end = 1208
    _globals["_COMPARISONOPERATOR"]._serialized_start = 1210
    _globals["_COMPARISONOPERATOR"]._serialized_end = 1281
    _globals["_WORLDMETADATA"]._serialized_start = 37
    _globals["_WORLDMETADATA"]._serialized_end = 194
    _globals["_MODELMETADATA"]._serialized_start = 196
    _globals["_MODELMETADATA"]._serialized_end = 321
    _globals["_MODEL"]._serialized_start = 323
    _globals["_MODEL"]._serialized_end = 376
    _globals["_ENTITY"]._serialized_start = 378
    _globals["_ENTITY"]._serialized_end = 429
    _globals["_STORAGEENTRY"]._serialized_start = 431
    _globals["_STORAGEENTRY"]._serialized_end = 473
    _globals["_STORAGEDIFF"]._serialized_start = 475
    _globals["_STORAGEDIFF"]._serialized_end = 551
    _globals["_ENTITYDIFF"]._serialized_start = 553
    _globals["_ENTITYDIFF"]._serialized_end = 608
    _globals["_ENTITYUPDATE"]._serialized_start = 610
    _globals["_ENTITYUPDATE"]._serialized_end = 684
    _globals["_QUERY"]._serialized_start = 686
    _globals["_QUERY"]._serialized_end = 755
    _globals["_CLAUSE"]._serialized_start = 758
    _globals["_CLAUSE"]._serialized_end = 900
    _globals["_KEYSCLAUSE"]._serialized_start = 902
    _globals["_KEYSCLAUSE"]._serialized_end = 943
    _globals["_MEMBERCLAUSE"]._serialized_start = 945
    _globals["_MEMBERCLAUSE"]._serialized_end = 1064
    _globals["_COMPOSITECLAUSE"]._serialized_start = 1066
    _globals["_COMPOSITECLAUSE"]._serialized_end = 1172
# @@protoc_insertion_point(module_scope)
