# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: world.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bworld.proto\x12\x05world\x1a\x0btypes.proto"\x11\n\x0fMetadataRequest":\n\x10MetadataResponse\x12&\n\x08metadata\x18\x01'
    b' \x01(\x0b\x32\x14.types.WorldMetadata"D\n\x18SubscribeEntitiesRequest\x12(\n\rentities_keys\x18\x01'
    b' \x03(\x0b\x32\x11.types.KeysClause"G\n\x19SubscribeEntitiesResponse\x12*\n\rentity_update\x18\x01'
    b' \x01(\x0b\x32\x13.types.EntityUpdate"6\n\x17RetrieveEntitiesRequest\x12\x1b\n\x05query\x18\x01'
    b' \x01(\x0b\x32\x0c.types.Query";\n\x18RetrieveEntitiesResponse\x12\x1f\n\x08\x65ntities\x18\x01'
    b" \x03(\x0b\x32\r.types.Entity2\xf8\x01\n\x05World\x12@\n\rWorldMetadata\x12\x16.world.MetadataRequest\x1a\x17.world.MetadataResponse\x12X\n\x11SubscribeEntities\x12\x1f.world.SubscribeEntitiesRequest\x1a"
    b" .world.SubscribeEntitiesResponse0\x01\x12S\n\x10RetrieveEntities\x12\x1e.world.RetrieveEntitiesRequest\x1a\x1f.world.RetrieveEntitiesResponseb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "world_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_METADATAREQUEST"]._serialized_start = 35
    _globals["_METADATAREQUEST"]._serialized_end = 52
    _globals["_METADATARESPONSE"]._serialized_start = 54
    _globals["_METADATARESPONSE"]._serialized_end = 112
    _globals["_SUBSCRIBEENTITIESREQUEST"]._serialized_start = 114
    _globals["_SUBSCRIBEENTITIESREQUEST"]._serialized_end = 182
    _globals["_SUBSCRIBEENTITIESRESPONSE"]._serialized_start = 184
    _globals["_SUBSCRIBEENTITIESRESPONSE"]._serialized_end = 255
    _globals["_RETRIEVEENTITIESREQUEST"]._serialized_start = 257
    _globals["_RETRIEVEENTITIESREQUEST"]._serialized_end = 311
    _globals["_RETRIEVEENTITIESRESPONSE"]._serialized_start = 313
    _globals["_RETRIEVEENTITIESRESPONSE"]._serialized_end = 372
    _globals["_WORLD"]._serialized_start = 375
    _globals["_WORLD"]._serialized_end = 623
# @@protoc_insertion_point(module_scope)
