name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up poetry environment
        uses: ./.github/actions/setup-poetry-env

      - name: Install mod_spatialite
        run: sudo apt-get update -y && sudo apt-get install -y libsqlite3-mod-spatialite
        shell: bash

      - name: Run tests
        run: make test

  format-and-typing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up poetry environment
        uses: ./.github/actions/setup-poetry-env

      - name: Run checks
        run: make check
